version: '3.7'

services:
  web:
    build:
      context: ./starnavi_test_task
      dockerfile: Dockerfile
    command: gunicorn starnavi_test_task.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - /static:/static
      - /media:/media
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin_dev
  nginx:
    build: ./nginx
    volumes:
      - /static:/static
      - /media:/media
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume:

