# Generated by Django 3.1.4 on 2020-12-11 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_network_api', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liker',
            field=models.ManyToManyField(related_name='post_liker', through='social_network_api.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
