# Generated by Django 3.1.4 on 2020-12-09 15:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 9, 15, 34, 33, 661985, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AccountActivity',
        ),
    ]
