# Generated by Django 3.1.4 on 2020-12-09 16:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201209_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_request',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 9, 16, 21, 58, 407420, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
