# Generated by Django 3.1.4 on 2020-12-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_last_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
